### ISSUE TITLE
New Powerpoint Document

### ISSUE THREAD

**Issue by cfrenz** [lizfrenz/owasp-vuln-mngmnt#4]
**Can you implement OWASP Vulnerability Management Guide at your place of work or business?**
Please state "yes" or "no' and explain why. E.g.: "not applicable", "I don't work in InfoSec", "too complicating". [...] Yes

**Is your feature request related to the OWASP VMG implementation? Please explain how.**
A clear and concise explanation of what the problem your request solves. [...] Yes 

**Please describe which of VMG cycles would host your addition? Detection, Reporting, Remediation.**
Interested in an updated power point

**Describe alternatives you've considered**
None

**Did you read the OWASP VMG? What are your thoughts**
Awesome

Pleae

**Comment by lizfrenz** [comment]
Thank you for reminding me!
